// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/node_modules/dumi/dist/client/theme-api/index.js';
