// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"docs/test":{"path":"test","id":"docs/test","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "__Users__foreverw__dev-core__KuangPF_Github__dumi-theme-antd__node_modules__dumi__dist__client__pages__404" */'/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/example/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "__Users__foreverw__dev-core__KuangPF_Github__dumi-theme-antd__node_modules__dumi__theme-default__layouts__DocLayout__index" */'/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/example/docs/index.md')),
'docs/test': React.lazy(() => import(/* webpackChunkName: "docs__test.md" */'/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/example/docs/test.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "__Users__foreverw__dev-core__KuangPF_Github__dumi-theme-antd__node_modules__dumi__dist__client__pages__Demo__index" */'/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
