// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/foreverw/dev-core/KuangPF_Github/dumi-theme-antd/node_modules/dumi/theme-default/slots/Hero/index.js';
